#!/usr/bin/env bash
# ============================================================
# Grafana Cloud → Alloy bootstrap
# Writes credentials.env, reloads systemd, restarts alloy.
# Re-run any time you rotate the token or change endpoints.
# ============================================================
set -euo pipefail

CRED_FILE="${HOME}/infra/observability/alloy/credentials.env"
QUADLET="${HOME}/.config/containers/systemd/alloy.container"

if [[ ! -f "${QUADLET}" ]]; then
  echo "ERROR: ${QUADLET} not found. Aborting." >&2
  exit 1
fi

prompt() {
  # prompt VAR "Question" [default]
  local __var="$1" __q="$2" __def="${3:-}" __val=""
  if [[ -n "${__def}" ]]; then
    read -r -p "${__q} [${__def}]: " __val
    __val="${__val:-${__def}}"
  else
    read -r -p "${__q}: " __val
  fi
  printf -v "${__var}" '%s' "${__val}"
}

prompt_secret() {
  local __var="$1" __q="$2" __val=""
  read -r -s -p "${__q}: " __val
  echo
  printf -v "${__var}" '%s' "${__val}"
}

echo "=== Grafana Cloud → Alloy setup ==="
echo
echo "Find these on grafana.com → My Account → your stack:"
echo "  • Prometheus: 'Send Metrics' panel (URL + Username/Instance ID)"
echo "  • Loki:       'Send Logs'    panel (URL + Username/Instance ID)"
echo "  • Token:      Access Policies → create policy with"
echo "                metrics:write + logs:write, then create a token"
echo

prompt HOSTNAME_LABEL "Host label for this machine" "$(hostname)"
echo
prompt GC_PROM_URL  "Grafana Cloud Prometheus push URL (e.g. https://prometheus-prod-XX-prod-us-east-0.grafana.net/api/prom/push)"
prompt GC_PROM_USER "Grafana Cloud Prometheus username / instance ID"
echo
prompt GC_LOKI_URL  "Grafana Cloud Loki push URL (e.g. https://logs-prod-NNN.grafana.net/loki/api/v1/push)"
prompt GC_LOKI_USER "Grafana Cloud Loki username / instance ID"
echo
prompt_secret GC_TOKEN "Grafana Cloud access-policy TOKEN (input hidden)"

if [[ -z "${GC_TOKEN}" ]]; then
  echo "ERROR: token is required." >&2
  exit 1
fi

mkdir -p "$(dirname "${CRED_FILE}")"
umask 077
cat > "${CRED_FILE}" <<EOF
# Generated by setup-grafana-cloud.sh on $(date -Iseconds)
# DO NOT COMMIT. chmod 600.
HOSTNAME_LABEL=${HOSTNAME_LABEL}
GC_PROM_URL=${GC_PROM_URL}
GC_PROM_USER=${GC_PROM_USER}
GC_LOKI_URL=${GC_LOKI_URL}
GC_LOKI_USER=${GC_LOKI_USER}
GC_TOKEN=${GC_TOKEN}
EOF
chmod 600 "${CRED_FILE}"
echo
echo "✓ wrote ${CRED_FILE} (chmod 600)"

# Ensure systemd-journal group membership so journald logs are readable
if ! id -nG | tr ' ' '\n' | grep -qx systemd-journal; then
  echo
  echo "WARNING: user '$(id -un)' is not in the 'systemd-journal' group."
  echo "         Journald log shipping will not work until you run:"
  echo "             sudo usermod -aG systemd-journal $(id -un)"
  echo "         …and log out/in (or reboot)."
fi

echo
echo "Reloading systemd user units…"
systemctl --user daemon-reload

echo "Restarting alloy.service…"
systemctl --user restart alloy.service

sleep 3
if systemctl --user is-active --quiet alloy.service; then
  echo "✓ alloy is running"
  echo
  echo "Live logs:    journalctl --user -u alloy.service -f"
  echo "Local UI:     http://127.0.0.1:12345"
  echo "Verify in Grafana Cloud → Explore → pick Loki / Prometheus datasource."
else
  echo "✗ alloy failed to start. Recent logs:" >&2
  journalctl --user -u alloy.service -n 40 --no-pager >&2 || true
  exit 1
fi
